version: '2.0'

services:
#  spark-config:
#    build: ./spark-ignite
#    image: spark-ignite

  spark-master:
    build: spark-master/.
    image: spark-master
    hostname: spark-master
    container_name: spark-master
    depends_on:
      - tonycox/spark-ignite
    # temp solving
    ports:
      # Spark master WebUI port
      - "8080:8080"
      # Spark master job submission port
      - "7077:7077"
    cpu_shares: 3000
    mem_limit: 2g
  
  spark-slave:
    build: spark-slave/.
    image: spark-slave
    depends_on:
      - tonycox/spark-ignite
    links:
      - spark-master
    cpu_shares: 3000
    mem_limit: 2g