version: '2.0'

services:
  spark-config:
    build: .
    image: spark-config

  spark-master:
    build: spark-master/.
    image: spark-master
    hostname: spark-master
    container_name: spark-master
    links: 
      - spark-config
    ports:
      # Spark master WebUI port
      - "8080:8080"
      # Spark master job submission port
      - "7077:7077"
    cpu_shares: 3000
    mem_limit: 2g
  
  spark-slave:
    build: spark-slave/.
    image: spark-slave
    links: 
      - spark-config
      - spark-master
    cpu_shares: 3000
    mem_limit: 2g

  ignite-node:
    image: apacheignite/ignite
    links:
      - spark-config